export const GET_USERS_START = "GET_USERS_START";
export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS";
export const CLEAR_USERS = "CLEAR_USERS";

export const GET_USER_AND_REPOS_START = "GET_USER_START";
export const GET_USER_AND_REPOS_SUCCESS = "GET_USER_SUCCESS";
